// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/popular": {
    params: {};
  };
  "/ranking": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/portfolio" | "/popular" | "/ranking";
  };
  "./layout.tsx": {
    id: "layout";
    page: "/portfolio" | "/popular" | "/ranking" | "/";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "routes/popular.tsx": {
    id: "routes/popular";
    page: "/popular";
  };
  "routes/ranking.tsx": {
    id: "routes/ranking";
    page: "/ranking";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};