// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "./layout.tsx": {
    id: "layout";
    page: "/";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};